version = 1
SPDX-PackageName = "btp-developer-guide"
SPDX-PackageSupplier = "Ekaterina Mitova (ekaterina.mitova@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-developer-guide"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and sap-docs/btp-developer-guide contributors"
SPDX-License-Identifier = "CC-BY-4.0"
